# Generated by Django 3.2.4 on 2022-11-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='token',
            new_name='social_id',
        ),
    ]
