# Generated by Django 3.2.4 on 2022-11-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='country',
            field=models.CharField(default='Khác', max_length=50),
        ),
    ]
