# Generated by Django 3.2.4 on 2022-11-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20221109_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image_cover',
            field=models.ImageField(default='/music.jpg', null=True, upload_to=''),
        ),
    ]
