# Generated by Django 3.2.4 on 2022-11-14 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='views',
        ),
    ]
