# Generated by Django 3.2.4 on 2022-11-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_sharesong'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
