# Generated by Django 3.2.4 on 2022-11-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_shareplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='hasLyric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='sentences',
            field=models.JSONField(null=True),
        ),
    ]
