# Generated by Django 3.2.4 on 2022-11-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_alter_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='sentences',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
