# Generated by Django 3.2.4 on 2022-11-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_auto_20221123_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isKaraoke',
            field=models.BooleanField(default=False),
        ),
    ]
