# Generated by Django 3.2.4 on 2022-11-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_song_iskaraoke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='isKaraoke',
            new_name='hasKaraoke',
        ),
    ]
