# Generated by Django 3.2.4 on 2022-11-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_rename_iskaraoke_song_haskaraoke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='country',
            field=models.CharField(choices=[('1', 'Việt Nam'), ('2', 'Âu Mỹ'), ('3', 'Hàn Quốc'), ('4', 'Nhật Bản'), ('5', 'Hoa Ngữ'), ('6', 'Hòa tấu'), ('7', 'Khác')], default='7', max_length=50),
        ),
    ]
