# Generated by Django 3.2.4 on 2022-11-25 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0017_alter_song_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='mv_likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
