# Generated by Django 3.2.4 on 2022-11-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(choices=[('1', 'Việt Nam'), ('1', 'US-UK'), ('1', 'K-POP'), ('1', 'Hoa Ngữ')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(default='A Popular Artist!'),
        ),
    ]
