# Generated by Django 3.2.4 on 2022-11-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
    ]
