# Generated by Django 3.2.4 on 2022-11-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_alter_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(choices=[('1', 'Việt Nam'), ('2', 'US-UK'), ('3', 'K-POP'), ('4', 'Hoa Ngữ'), ('5', 'Nhật Bản'), ('6', 'Khác')], default='1', max_length=50),
        ),
    ]
