# Generated by Django 3.2.4 on 2022-11-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_shareplaylist'),
        ('comment', '0002_auto_20221118_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_comments', to='songs.playlist'),
        ),
    ]
